image: registry.cmusatyalab.org/coda/coda-packaging/coda-build

variables:
  CCACHE_DIR: ${CI_PROJECT_DIR}/.cache/ccache
  PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit

before_script:
  - mkdir -p ${CCACHE_DIR}
  - export CCACHE_BASEDIR="${PWD}"
  - export CCACHE_MAXSIZE="500M"
  - export CCACHE_NOHASHDIR=true
  - export CC="/usr/bin/ccache gcc"
  - export CXX="/usr/bin/ccache g++"

cache:
  paths:
    - ${CCACHE_DIR}
    - ${PRE_COMMIT_HOME}

test_build:
  stage: build
  script:
    - tools/version_check.sh
    - ./bootstrap.sh
    - ./configure --prefix=/usr --with-lua
    - pre-commit run --all-files
    - make all
  except:
    - tags
    - master
    - /^coda-.*$/

build_source:
  stage: build
  script:
    - tools/version_check.sh
    - ./bootstrap.sh --fix-versions
    - ./configure --prefix=/usr --with-lua
    - pre-commit run --all-files
    - make distcheck
  artifacts:
    expire_in: 1 week
    paths:
      - "coda-*.tar*"
  only:
    - tags
    - master
    - /^coda-.*$/

test_doc:
  stage: build
  script:
    - doxygen doxygen/Doxyfile
  except:
    - master

pages:
  stage: build
  script:
    - doxygen doxygen/Doxyfile
    - mv doxygen/html/ public/
  artifacts:
    expire_in: 1 week
    paths:
      - public
  only:
    - master
