image: registry.cmusatyalab.org/coda/coda-packaging/coda-build

# should be a no-op if the submitter used the pre-commit hooks
post_commit:
  stage: .pre
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    key: precommit
    paths:
      - $PRE_COMMIT_HOME
  script:
    - pre-commit run --all-files
    - tools/version_check.sh

.build_template:
  stage: build
  variables:
    CCACHE_DIR: ${CI_PROJECT_DIR}/.cache/ccache
    FIXVER: ""
    TARGET: all
  cache:
    key: default
    paths:
      - $CCACHE_DIR
  before_script:
    - mkdir -p "$CCACHE_DIR"
    - export CCACHE_BASEDIR="${PWD}"
    - export CCACHE_MAXSIZE="500M"
    - export CCACHE_NOHASHDIR=true
    - export CC="/usr/bin/ccache gcc"
    - export CXX="/usr/bin/ccache g++"
  script:
    - ./bootstrap.sh $FIXVER
    - ./configure --prefix=/usr --with-lua
    - make $TARGET

test_build:
  extends: .build_template
  except:
    - tags
    - master
    - /^coda-.*$/

build_source:
  extends: .build_template
  variables:
    FIXVER: "--fix-versions"
    TARGET: distcheck
  artifacts:
    expire_in: 1 week
    paths:
      - "coda-*.tar*"
  only:
    - tags
    - master
    - /^coda-.*$/

test_doc:
  stage: build
  script:
    - doxygen doxygen/Doxyfile
  except:
    - master

pages:
  stage: build
  script:
    - doxygen doxygen/Doxyfile
    - mv doxygen/html/ public/
  artifacts:
    expire_in: 1 week
    paths:
      - public
  only:
    - master
