# Use Debian-based official GCC image
# see https://hub.docker.com/_/gcc/
image: gcc

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - mkdir -p ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/ccache
  - export PATH=/usr/lib/ccache:${PATH}

cache:
  paths:
    - ccache/

sources:
  stage: build
  script:
    - apt-get update -y -qq
    - apt-get install -y -qq --no-install-recommends automake ccache bison flex pkg-config python systemd liblua5.1-0-dev libncurses5-dev libreadline-dev libuv1-dev
    - tools/version_check.sh
    - ./bootstrap.sh --fix-versions
    - ./configure --prefix=/usr --with-lua
    - make distcheck dist-xz
  artifacts:
    expire_in: 1 week
    paths:
      - "coda-*.tar*"

test_pages:
  stage: build
  image: alpine
  before_script:
    - apk --no-cache add doxygen graphviz ttf-freefont
  script:
    - doxygen doxygen/Doxyfile
  except:
    - master

pages:
  stage: build
  image: alpine
  before_script:
    - apk update && apk add doxygen graphviz
  script:
    - doxygen doxygen/Doxyfile
    - mv doxygen/html/ public/
  artifacts:
    expire_in: 1 week
    paths:
      - public
  only:
    - master
