repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: check-release
        name: Check if release version is current
        entry: tools/check-blurb --release
        language: script
        stages: [commit,merge-commit]
      - id: check-year
        name: Check if copyright year is current
        entry: tools/check-blurb --year
        language: script
        stages: [commit,merge-commit]
      - id: clang-format
        name: Format source with Clang format
        entry: tools/check-clang-format -style=file -i
        language: system
        types_or: [c, c++]

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: Reorder python imports with isort

  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        name: Format python code with black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: Linting python code with flake8
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
      - id: markdownlint
        name: Lint markdown documentation

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
