sudo: false

language: c
cache: ccache

addons:
  apt:
    packages:
    - libreadline-dev
    - libncurses5-dev
    - liblua5.1-0-dev
    - libuv1-dev
    - flex
    - bison
    - pkg-config
    - python
    - automake

before_script:
  - ./bootstrap.sh
  - ./configure --prefix=/usr --with-lua
script:
  - make -j2 distcheck
