sudo: false

language: c
cache: ccache

addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-6.0
    packages:
    - libreadline-dev
    - libncurses5-dev
    - liblua5.1-0-dev
    - flex
    - bison
    - pkg-config
    - python
    - automake
    - libllvm6.0
    - clang-format-6.0

before_script:
  - ./bootstrap.sh
  - ./configure --prefix=/usr --with-lua --without-libuv
script:
  - DISTCHECK_CONFIGURE_FLAGS=--without-libuv make -j2 distcheck
